<?php

  function cipher_menu() {
    $items['cipher'] = array(
      'title' => 'Encrypt Phrase',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('cipher_form'),
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
    );
    $items['encryption_display'] = array(
      'title' => 'Encrypted Phrase Display',
      'page callback' => 'cipher_display',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    );
    return $items;
  }

  function cipher_form() {
    $form['phrase'] = array(
      '#title' => 'Phrase',
      '#type' => 'textfield',
      '#description' => t('Please enter a phrase to encrypt.'),
      '#element_validate' => array('element_validate_text'),
      '#required' => TRUE,
    );
    $form['direction'] = array(
      '#title' => 'Direction',
      '#type' => 'textfield',
      '#description' => t('Please enter the direction to use for encryption.'),
      '#element_validate' => array('element_validate_direction'),
      '#required' => TRUE,
    );
    $form['shift'] = array(
      '#title' => 'Shift Amount',
      '#type' => 'textfield',
      '#description' => t('Please enter the number of spaces to shift for encryption.'),
      '#element_validate' => array('element_validate_number'),
      '#required' => TRUE,
    );
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Encrypt!',
    );
    return $form;
  }

  function element_validate_direction($element) {
    if ($element['#value'] != 'right' && $element['#value'] != 'left') {
      form_error($element, t("Please enter only 'left' or 'right' as a direction."));
    }
  }

  function element_validate_text($element) {
    if (preg_match('/[^a-z\s\'_.,!"$#&:;\/]/', $element['#value'])) {
      form_error($element, t('Please enter only lowercase letters and punctuation.'));
    }
  }

  function cipher_form_submit($form, &$form_state) {
    $direction = $form_state['values']['direction'];
    $shift = $form_state['values']['shift'];
    $phrases = $form_state['values']['phrase'];
    $words = str_split($phrases);
    $new_word = [];
    $z_pos = ord('z');
    $a_pos = ord('a');

    foreach($words as $word) {
      if ($direction == 'right') {
        $increment = ord($word) + $shift;
      } elseif ($direction == 'left') {
        $increment = ord($word) - $shift;
      }
      $letters = str_split($word);
      foreach($letters as $letter) {
        if (preg_match('/[a-z]/', $letter)) {
          if ($increment <= $z_pos && ord($increment >= $a_pos)) {
            $new_letter = array(chr($increment));
          } elseif ($increment > $z_pos) {
            $num_past_end = (($increment) - $z_pos) - 1;
            $new_letter = array((chr(ord('a') + $num_past_end)));
          } elseif ($increment < $a_pos) {
            $num_before_beginning = ($a_pos - ($increment) - 1);
            $new_letter = array((chr(ord('z') - $num_before_beginning)));
          }
        } elseif (preg_match('/[\s\'_.,!"$#&:;\/]/', $letter)) {
          $new_letter = array($letter);
        }
        $new_word = array_merge($new_word, $new_letter);
      }
    }

    $_SESSION['cipher'] = implode("", $new_word);

    $form_state['redirect'] = 'encryption_display';
  }

  function cipher_display() {
    return $_SESSION['cipher'];
  }
