<?php
  function cipher_menu() {
    $items['cipher'] = array(
      'title' => 'Encrypt Phrase',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('cipher_form'),
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
    );
    $items['encryption_display'] = array(
      'title' => 'Encrypted Phrase Display',
      'page callback' => 'cipher_display',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    );
    return $items;
  }

  function cipher_form() {
    $form['phrase'] = array(
      '#title' => 'Phrase',
      '#type' => 'textfield',
      '#description' => t('Please enter a phrase to encrypt.'),
      '#required' => TRUE,
    );
    $form['direction'] = array(
      '#title' => 'Direction',
      '#type' => 'textfield',
      '#description' => t('Please enter the direction to use for encryption.'),
      '#required' => TRUE,
    );
    $form['shift'] = array(
      '#title' => 'Shift Amount',
      '#type' => 'textfield',
      '#description' => t('Please enter the number of spaces to shift for encryption.'),
      '#required' => TRUE,
    );
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Encrypt!',
    );
    return $form;
  }

  function cipher_form_submit($form, &$form_state) {
    // $new_word = [];
    $phrase_words = $form_state['values']['phrase'];
    // $phrase_words = explode(" ", strtolower($form_state['values']['phrase']));
    $direction = $form_state['values']['direction'];
    $shift = $form_state['values']['shift'];
    $new_word = chr(ord($phrase_words) + $shift);

    //
    // foreach($phrase_words as $word) {
    //   $letters = explode("", $word);
    //   foreach($letters as $letter) {
    //     $new_letter = ++$letter;
    //     array_push($new_word, $new_letter);
    //   }
    // }

    $_SESSION['cipher'] = $new_word;

    $form_state['redirect'] = 'encryption_display';
  }

  function cipher_display() {
    return $_SESSION['cipher'];
  }
