<?php

  function cipher_menu() {
    $items['cipher'] = array(
      'title' => 'Encrypt Phrase',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('cipher_form'),
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
    );
    $items['encryption_display'] = array(
      'title' => 'Encrypted Phrase Display',
      'page callback' => 'cipher_display',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    );
    return $items;
  }

  function cipher_form() {
    $form['phrase'] = array(
      '#title' => 'Phrase',
      '#type' => 'textfield',
      '#description' => t('Please enter a phrase to encrypt.'),
      '#required' => TRUE,
    );
    $form['direction'] = array(
      '#title' => 'Direction',
      '#type' => 'textfield',
      '#description' => t('Please enter the direction to use for encryption.'),
      '#required' => TRUE,
    );
    $form['shift'] = array(
      '#title' => 'Shift Amount',
      '#type' => 'textfield',
      '#description' => t('Please enter the number of spaces to shift for encryption.'),
      '#required' => TRUE,
    );
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Encrypt!',
    );
    return $form;
  }

  function cipher_phrase($phrases, $direction, $shift) {
    $words = str_split($phrases);


    return $new_word;

  }

  function cipher_form_submit($form, &$form_state) {
    $direction = $form_state['values']['direction'];
    $shift = $form_state['values']['shift'];
    $phrases = $form_state['values']['phrase'];
    // $cipher = cipher_phrase($phrases, $direction, $shift);
    $words = str_split($phrases);
    $new_word = [];
    foreach($words as $word) {
      $new_letter = array((chr(ord($word) + $shift)));
      $new_word = array_merge($new_word, $new_letter);
    }

    $_SESSION['cipher'] = implode("", $new_word);

    $form_state['redirect'] = 'encryption_display';
  }

  function cipher_display() {
    return $_SESSION['cipher'];
  }
